### PR TITLE
feat(helm): upgrade components

### PR DESCRIPTION
**Pull request by azman0101**
- `helm-secrets` is deprecated so I changed it for the recommanded active fork https://github.com/jkroepke/helm-secrets
- Also added helm-gcs and helm-diff
- lock helm plugin versions

### CODE REVIEW

**Comment by monotek** [comment]
Sorry, not workin at kiwigrid anmyore os i can't release it.
But imho it's also not used anymore so you might want to fork...

**Comment by jekkel** [comment]
> i can't release it

I elevated your access - so if you feel the contribution can be released: please do so.

**Comment by pesimon** [comment]
@jekkel @monotek Any progress on releasing those valuable changes from @azman0101 👍   
Let me know if anything is needed, I'm happy to do some testing.

**Comment by giddel** [comment]
Is there any chance to get this PR merged?

**Pull request merged**
